### ISSUE TITLE
Weather

### ISSUE THREAD

**Issue by teeganduong** [Dungeongate/Smart-Mirror-Display#2]
A user can view the current local weather.

**Comment by ryanfaulkenberry100** [comment]
Does anybody remember the info we got on weather rss from our classmates? If so, go ahead and drop the knowledge here.

**Comment by RestfulLeo23** [comment]
I think it was called Open Weather Maps.

**Comment by ryanfaulkenberry100** [comment]
Raspbian has a weather util called, appropriately, "weather-util" that will probably be easy to script in bash. Leaving this comment here so I don't forget what it's called.

**Comment by RestfulLeo23** [comment]
Weather has been added to the software.
